'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ChartLineUp } from '@phosphor-icons/react';
import { postApi, type PostItem } from '@/services/postApi';

type Daily = { date: string; views: number; likes: number; replies: number; reposts: number; followers: number };
export default function InsightsPage() {
  const [report, setReport] = useState<{ days: number; totals: any; daily: Daily[]; topPosts: { post: PostItem; views: number; likes: number; replies: number; reposts: number }[] } | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { postApi.getInsights().then(setReport).catch(() => setError('Đăng nhập để xem thống kê tác giả.')); }, []);
  return <main className="mx-auto min-h-[calc(100dvh-4rem)] max-w-5xl px-4 py-10 sm:px-6"><Link href="/posts" className="text-sm font-semibold text-accent">← Bảng tin</Link><header className="mt-4 flex items-center gap-3 border-b border-line pb-6"><ChartLineUp size={28} className="text-accent" /><div><p className="text-xs font-bold uppercase tracking-widest text-accent">Dành cho tác giả</p><h1 className="mt-1 font-serif text-3xl font-bold text-ink">Thống kê</h1></div></header>{error && <p className="mt-8 rounded-2xl border border-line p-6 text-center text-muted">{error}</p>}{report && <><section className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3">{[['Lượt xem', report.totals.views], ['Người theo dõi', report.totals.followers], ['Theo dõi mới', report.totals.newFollowers]].map(([label, value]) => <article key={String(label)} className="rounded-2xl border border-line bg-surface p-5"><p className="text-sm text-muted">{label}</p><p className="mt-2 text-2xl font-bold text-ink">{Number(value).toLocaleString('vi-VN')}</p></article>)}</section><section className="mt-6 rounded-2xl border border-line bg-surface p-5"><h2 className="font-bold text-ink">Hoạt động trong {report.days} ngày qua</h2><div className="mt-5 space-y-3">{(['views', 'likes', 'replies', 'reposts', 'followers'] as const).map(metric => { const total = report.daily.reduce((sum, row) => sum + row[metric], 0); const max = Math.max(1, ...report.daily.map(row => row[metric])); return <div key={metric}><div className="mb-1 flex justify-between text-xs text-muted"><span>{{ views: 'Lượt xem', likes: 'Lượt thích', replies: 'Bình luận', reposts: 'Đăng lại', followers: 'Người theo dõi' }[metric]}</span><span>{total.toLocaleString('vi-VN')}</span></div><div className="flex h-3 items-end gap-[2px]">{report.daily.map(day => <span key={day.date} title={`${day.date}: ${day[metric]}`} className="min-w-[2px] flex-1 rounded-sm bg-accent/80" style={{ height: `${Math.max(5, day[metric] / max * 100)}%` }} />)}</div></div>; })}</div></section><section className="mt-6 rounded-2xl border border-line bg-surface p-5"><h2 className="font-bold text-ink">Bài viết nổi bật</h2><div className="mt-3 divide-y divide-line">{report.topPosts.map(row => <Link href={`/posts/${row.post.slug || row.post.id}`} key={row.post.id} className="flex items-center justify-between gap-4 py-3"><span className="line-clamp-1 text-sm font-semibold text-ink">{row.post.title}</span><span className="shrink-0 text-xs text-muted">{row.views} xem · {row.likes} thích · {row.replies} phản hồi</span></Link>)}</div></section></>}</main>;
}
